# Generated by Django 3.0 on 2021-06-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HallBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhl',
            name='address',
            field=models.CharField(max_length=70),
        ),
    ]
