# Generated by Django 3.0 on 2021-06-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HallBooking', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(default=25000),
        ),
        migrations.AddField(
            model_name='booking',
            name='cardno',
            field=models.CharField(default='XXXXXXXXXXXXX', max_length=13),
        ),
        migrations.AddField(
            model_name='booking',
            name='cvv',
            field=models.CharField(default='XXX', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='expmonth',
            field=models.IntegerField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='expyear',
            field=models.IntegerField(choices=[('1', '2021'), ('2', '2022'), ('3', '2023'), ('4', '2024'), ('5', '2025'), ('6', '2026'), ('7', '2017'), ('8', '2028')], null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
